title:            Affective Cerebellar Research lab
logo:             assets/img/cover.png
description:      ''
tagline:          ''



show_downloads: false
google_analytics:
plugins:
  - jekyll-remote-theme
remote_theme: zivong/jekyll-theme-hydure
